In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
import subprocess
import re
import itertools
import functools
import collections
import tqdm

In [3]:
import requests

day_num = 20

cookies = {
    'session': '53616c7465645f5f465a94508e1037cf931dedaf44e298b1be500ec71305ff01432a6584b1fe922ea5bab725d96f17b1'
}

url = f'http://adventofcode.com/2017/day/{day_num}/input'

r = requests.get(url, cookies=cookies)

lines = [i.strip() for i in r.text.split('\n')][:-1]

print(f'{len(lines)} lines')

for i in lines[:5]:
    print(i[:10])

1000 lines
p=<-1027,-
p=<-1846,-
p=<338,820
p=<-3162,-
p=<1780,55


In [4]:
lines[0]

'p=<-1027,-979,-188>, v=<7,60,66>, a=<9,1,-7>'

In [86]:
pos = []
vel = []
acc = []

for i in lines:
    parts = re.split(r'[pva =<,>]*', i)
    parts = [*filter(bool, parts)]
    parts = [*map(int, parts)]
    
    pos.append(parts[:3])
    vel.append(parts[3:6])
    acc.append(parts[6:])

pos = array(pos)
vel = array(vel)
acc = array(acc)

/Users/abra/brew/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py:212: FutureWarning: split() requires a non-empty pattern match.
  return _compile(pattern, flags).split(string, maxsplit)


In [28]:
testlines = ['p=< 3,0,0>, v=< 2,0,0>, a=<-1,0,0>',
'p=< 4,0,0>, v=< 0,0,0>, a=<-2,0,0>']

pos = []
vel = []
acc = []

for i in testlines:
    parts = re.split(r'[pva =<,>]*', i)
    parts = [*filter(bool, parts)]
    parts = [*map(int, parts)]
    
    pos.append(parts[:3])
    vel.append(parts[3:6])
    acc.append(parts[6:])

pos = array(pos)
vel = array(vel)
acc = array(acc)

/Users/abra/brew/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py:212: FutureWarning: split() requires a non-empty pattern match.
  return _compile(pattern, flags).split(string, maxsplit)


In [15]:
for i in range(100):
    vel += acc
    pos += vel

In [17]:
sum(abs(pos), axis=1)

array([ 4847, 10096])

In [37]:
for i in range(100000):
    vel += acc
    pos += vel

In [38]:
dists = sum(abs(pos), axis=1)
argmin(dists)

119

In [41]:
a = zeros((9, 3), dtype=int)

In [45]:
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [50]:
vals, index = unique(a, axis=0, return_index=True)

In [51]:
a[index]

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]])

In [71]:
argsort?

In [81]:
argsort(pos, axis=0, order=(0, 1, 2))

ValueError: Cannot specify order when the array has no fields.

In [80]:
argsort?

In [79]:
argsort(pos)

array([[1, 0, 2],
       [0, 2, 1],
       [0, 1, 2],
       ..., 
       [0, 1, 2],
       [0, 1, 2],
       [1, 2, 0]])

In [85]:
[*filter(lambda x: x % 2 == 0, arange(10))]

[0, 2, 4, 6, 8]

In [93]:
poses = []
for i in tqdm.trange(1000):
    hashes = sum(pos * array([783218, 383972819637821, 1]), axis=1)
    
    counter = collections.Counter(hashes)
    
    index = [j for j in range(len(pos)) if counter[hashes[j]] == 1]
    
    pos = pos[index]
    vel = vel[index]
    acc = acc[index]
    
    poses.append(len(index))
    
    vel += acc
    pos += vel

100%|██████████| 1000/1000 [00:00<00:00, 2048.41it/s]


In [94]:
pos.shape

(471, 3)

In [ ]:
plot(pos)

In [59]:
pos.shape

(561, 3)